-- CreateEnum
CREATE TYPE "LeadType" AS ENUM ('STUDENT', 'BUSINESS');

-- CreateEnum
CREATE TYPE "LeadPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- CreateEnum
CREATE TYPE "LostReason" AS ENUM ('FINANCIAL_ISSUE', 'PARENTS_REJECTED', 'JOINED_ANOTHER_INSTITUTE', 'NO_TIME', 'NOT_ELIGIBLE', 'BUDGET_ISSUE', 'COMPETITOR_WON', 'ALREADY_HIRED_AGENCY', 'INTERNAL_TEAM', 'POSTPONED', 'CANCELLED', 'NO_RESPONSE');

-- CreateEnum
CREATE TYPE "TeamRole" AS ENUM ('FOUNDER', 'SALES');

-- CreateEnum
CREATE TYPE "LeadEventType" AS ENUM ('LEAD_CREATED', 'RE_ENQUIRY', 'ASSIGNED', 'REASSIGNED', 'CALL_ATTEMPTED', 'WHATSAPP_SENT', 'FOLLOW_UP_SCHEDULED', 'STATUS_CHANGED', 'NOTE_ADDED', 'CONVERTED');

-- CreateEnum
CREATE TYPE "ReassignReason" AS ENUM ('SLA_BREACH', 'UNAVAILABLE', 'MANUAL_OVERRIDE');
