-- AlterEnum
BEGIN;
CREATE TYPE "LeadStatus_new" AS ENUM ('NEW', 'ASSIGNED', 'FIRST_CALL', 'INTERESTED', 'CALLBACK_REQUESTED', 'NOT_RESPONDED', 'NOT_INTERESTED', 'COUNSELLING', 'ENROLLMENT', 'PAYMENT', 'INITIAL_CONTACT', 'WHATSAPP_DISCUSSION', 'DISCOVERY_CALL', 'REQUIREMENTS_GATHERING', 'PROPOSAL_SENT', 'NEGOTIATION', 'PROJECT_APPROVED', 'DEVELOPMENT_STARTED', 'CONVERTED', 'LOST');
ALTER TABLE "public"."Lead" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Lead" ALTER COLUMN "status" TYPE "LeadStatus_new" USING ("status"::text::"LeadStatus_new");
ALTER TYPE "LeadStatus" RENAME TO "LeadStatus_old";
ALTER TYPE "LeadStatus_new" RENAME TO "LeadStatus";
DROP TYPE "public"."LeadStatus_old";
ALTER TABLE "Lead" ALTER COLUMN "status" SET DEFAULT 'NEW';
COMMIT;
